import Head from 'next/head'
import dynamic from "next/dynamic";
import Image from 'next/image'
import React, { useCallback, useState } from 'react'
import { useWallet } from 'use-wallet'
import { Button, Text } from "@geist-ui/react";
import { getEIP712Profile } from '../constant/EIP712Domain'
import { useSigner } from '../hooks/useSigner'
import styles from '../styles/Home.module.css'
import { useRecoilState } from 'recoil';
import { chainIdState } from '../stateAtoms/chainId.atom';
// dynamic load
const CreateSnippet = dynamic(() => import("../components/CreateSnippet"), { ssr: false }) ;
const SnippetCreated = dynamic(() => import('../components/SnippetCreated'), { ssr: false });


export default function Home() {
  const wallet = useWallet()
  const [chainId] = useRecoilState(chainIdState)

  const [uploadedHash, setUploadedHash] = useState('')

  const { signer, isSignerReady } = useSigner()

  if (uploadedHash) {
    return <SnippetCreated uploadedHash={uploadedHash} />
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Unlock Content by ERC20</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text h1>
          Unlock with ERC20 Demo
        </Text>

        {
          !isSignerReady(signer) ? 
            <>
            <p>Connected to ChainId { chainId }</p>
            <p>Connect Wallet by</p>
            <Button onClick={() => wallet.connect('injected')}>MetaMask</Button>
            {/* <button onClick={() => wallet.connect('walletconnect')}>Wallet Connect</button> */}
          </>
          : 
            <>
              <CreateSnippet onSent={(res) => {
                setUploadedHash(res.hash)
              }} />

              {uploadedHash && <a href={`https://ipfs.fleek.co/ipfs/${uploadedHash}`} target="_blank">Go IPFS to See RAW</a>}
              {uploadedHash && <a href={`/${uploadedHash}`}>Decrypt and See</a>}

              {/* <Button onClick={() => signMsg() }>Sign</Button>
              <Button onClick={() => wallet.reset()}>Disconnect</Button> */}
          </>
        }

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
