import Head from 'next/head'
import NextLink from "next/link";
import React, {  } from 'react'
import { Button, Text, useClipboard, useToasts } from "@geist-ui/react";
import styles from '../styles/Home.module.css'
import styled from 'styled-components';

type Params = {
    uploadedHash: string;
}

const ActionsCard = styled.div`
    align-items: center;
    text-align: center;
    button {
        margin: 4px;
    }
`

export default function SnippetCreated({ uploadedHash, ...params }: Params) {
  const [, setToast] = useToasts()
  const { copy } = useClipboard()
  const fullUrl = `https://${window.location.hostname}/${uploadedHash}/`
    return <div className={styles.container}>
      <Head>
        <title>Unlock Content by ERC20</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text h1>
          🎉 Upload successfully 🎉  
        </Text>
        <Text h4>
          You can share your snippet now or <a href={`/${uploadedHash}`}>just have a look 👀</a>
        </Text>
        <ActionsCard>
          <NextLink href={`/${uploadedHash}/requirement`}>
            <Button shadow type="secondary">🔒 Lock with requirement</Button>
          </NextLink>
          <Button shadow auto onClick={() => {
            copy(fullUrl)
            setToast({
              type: 'success',
              text: 'Link copied, you can share it now.'
            })
          }}> 🔗 Copy Link & Share </Button>
          <Button shadow onClick={() => window.location.reload()} >🙋 Post another snippet</Button>
        </ActionsCard>
      </main>
      </div>
}